---
- name: copy source
  copy:
    src: ubuntu_source/source_{{ Source }}_ubuntu{{ ansible_distribution_version }}.list
    dest: /etc/apt/sources.list
    backup: yes
    directory_mode: 664

- name: apt update
  apt:
    update_cache: yes

- name: apt-get -f install
  shell: apt-get -f install

- name: apt upgrade
  apt:
   upgrade: yes
